<a href="https://colab.research.google.com/github/Luffyapo93/Pool/blob/main/EXAMEN_FINAL_PRACTICO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Parte 1: Fundamentos NumPy

1.-

In [5]:
import numpy as np

# Crear el arreglo NumPy del 1 al 20
arreglo_numpy = np.arange(1, 21)

# Mostrar el arreglo
print(arreglo_numpy)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


2.-

In [4]:
# Seleccionar los múltiplos de 3
multiplos_de_3 = arreglo_numpy[arreglo_numpy % 3 == 0]

print("-------------------------------------------------------------")
# Mostrar los múltiplos de 3
print("Múltiplos de 3:")
print(multiplos_de_3)

-------------------------------------------------------------
Múltiplos de 3:
[ 3  6  9 12 15 18]


3.-

In [8]:
import numpy as np

matriz = np.random.rand(5, 5)
print(matriz)


[[0.15468118 0.11352536 0.48794417 0.97990708 0.88957777]
 [0.18201562 0.14842653 0.89944155 0.10274079 0.4419001 ]
 [0.28595909 0.86828128 0.93026245 0.43500188 0.87338984]
 [0.11832987 0.82308339 0.14753676 0.90053564 0.87188852]
 [0.67487422 0.20705161 0.79362097 0.76968193 0.36470899]]


4.-

In [7]:
import numpy as np

# Generar la matriz aleatoria 5x5
matriz = np.random.rand(5, 5)

# Calcular la media
media = np.mean(matriz)

# Calcular la desviación estándar
desviacion = np.std(matriz)

# Calcular el valor máximo
maximo = np.max(matriz)

# Mostrar resultados
print("Matriz:\n", matriz)
print("Media:", media)
print("Desviación estándar:", desviacion)
print("Valor máximo:", maximo)


Matriz:
 [[0.56965685 0.64270018 0.01109559 0.91648276 0.06940388]
 [0.00512368 0.06062648 0.89400674 0.95162466 0.22238781]
 [0.40135946 0.39767834 0.89347402 0.23234521 0.72746256]
 [0.83024773 0.93274768 0.67380191 0.20393395 0.14041655]
 [0.20994999 0.02584379 0.54784078 0.01712272 0.07622973]]
Media: 0.42614252208391096
Desviación estándar: 0.34216118657570077
Valor máximo: 0.9516246585367407


5.-

In [9]:
import numpy as np

# Generar la matriz aleatoria 5x5
matriz = np.random.rand(5, 5)

# Transformar la matriz en un vector 1D
vector = matriz.flatten()

# Mostrar resultados
print("Matriz original:\n", matriz)
print("Vector de una dimensión:\n", vector)


Matriz original:
 [[0.03107612 0.19747264 0.33829989 0.93811883 0.89603219]
 [0.78583129 0.17613563 0.49386377 0.88159629 0.62835107]
 [0.50232328 0.20453259 0.23419349 0.50479389 0.68040411]
 [0.16222084 0.01835799 0.0886528  0.68810751 0.23478778]
 [0.93711985 0.30306209 0.86229396 0.54034248 0.86863193]]
Vector de una dimensión:
 [0.03107612 0.19747264 0.33829989 0.93811883 0.89603219 0.78583129
 0.17613563 0.49386377 0.88159629 0.62835107 0.50232328 0.20453259
 0.23419349 0.50479389 0.68040411 0.16222084 0.01835799 0.0886528
 0.68810751 0.23478778 0.93711985 0.30306209 0.86229396 0.54034248
 0.86863193]


Parte 2: Fundamentos Pandas

1.-

In [10]:
import pandas as pd

data = {'Nombre': ['Ana', 'Luis', 'María', 'Pedro', 'Sofía'],
        'Edad': [20, 21, 19, 22, 20],
        'Nota_Matemáticas': [18, 15, 16, 12, 19],
        'Nota_IA': [17, 14, 18, 13, 20]}

df = pd.DataFrame(data)

print(df)

  Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
1   Luis    21                15       14
2  María    19                16       18
3  Pedro    22                12       13
4  Sofía    20                19       20


2.-

In [11]:
# Calcular el promedio de cada columna numérica
promedio_columnas = df.mean(numeric_only=True)

# Mostrar los promedios
print("Promedio de cada columna numérica:")
print(promedio_columnas)

Promedio de cada columna numérica:
Edad                20.4
Nota_Matemáticas    16.0
Nota_IA             16.4
dtype: float64


3.-

In [12]:
# Filtrar estudiantes con nota de IA mayor a 15
estudiantes_ia_alta = df[df['Nota_IA'] > 15]

# Mostrar el DataFrame filtrado
print("Estudiantes con Nota_IA mayor a 15:")
print(estudiantes_ia_alta)

Estudiantes con Nota_IA mayor a 15:
  Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
2  María    19                16       18
4  Sofía    20                19       20


4.-

In [13]:
# Agregar una nueva columna 'Promedio'
df['Promedio'] = (df['Nota_Matemáticas'] + df['Nota_IA']) / 2

# Mostrar el DataFrame con la nueva columna
print("DataFrame con la columna 'Promedio':")
print(df)

DataFrame con la columna 'Promedio':
  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
0    Ana    20                18       17      17.5
1   Luis    21                15       14      14.5
2  María    19                16       18      17.0
3  Pedro    22                12       13      12.5
4  Sofía    20                19       20      19.5


5.-

In [14]:
# Ordenar el DataFrame por la columna 'Promedio' de mayor a menor
df_ordenado_promedio = df.sort_values(by='Promedio', ascending=False)

# Mostrar el DataFrame ordenado
print("DataFrame ordenado por Promedio (de mayor a menor):")
display(df_ordenado_promedio)

DataFrame ordenado por Promedio (de mayor a menor):


Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
4  Sofía    20                19       20      19.5
0    Ana    20                18       17      17.5
2  María    19                16       18      17.0
1   Luis    21                15       14      14.5
3  Pedro    22                12       13      12.5

Parte 3: Algoritmia aplicada

1.-

In [15]:
def analizar_lista(numeros):
    if not numeros:
        return "La lista está vacía."

    mayor = max(numeros)
    menor = min(numeros)
    promedio = sum(numeros) / len(numeros)

    return mayor, menor, promedio

# Ejemplo de uso:
lista = [5, 10, 3, 8, 2]
resultado = analizar_lista(lista)

print("Número mayor:", resultado[0])
print("Número menor:", resultado[1])
print("Promedio:", resultado[2])


Número mayor: 10
Número menor: 2
Promedio: 5.6


2.-

In [16]:
import numpy as np

def sigmoide(x):
    return 1 / (1 + np.exp(-x))

# Arreglo de ejemplo
x = np.array([-2, -1, 0, 1, 2])

# Aplicar la función sigmoide
resultado = sigmoide(x)

print("Entrada:", x)
print("Salida sigmoide:", resultado)


Entrada: [-2 -1  0  1  2]
Salida sigmoide: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


3.-

In [17]:
import pandas as pd

# Ejemplo de DataFrame
data = {
    'Estudiante': ['Ana', 'Luis', 'María', 'Juan'],
    'Promedio': [15, 13, 16, 12]
}

df = pd.DataFrame(data)

# Función para clasificar
def clasificar_estudiantes(df):
    # Crear la columna 'Estado' con condiciones
    df['Estado'] = df['Promedio'].apply(lambda x: 'Aprobado' if x >= 14 else 'Desaprobado')
    return df

# Aplicar la función
df_clasificado = clasificar_estudiantes(df)

print(df_clasificado)


  Estudiante  Promedio       Estado
0        Ana        15     Aprobado
1       Luis        13  Desaprobado
2      María        16     Aprobado
3       Juan        12  Desaprobado


Parte 4: Mini-proyecto

In [18]:
import pandas as pd

# Datos iniciales
datos = {
    'Producto': ['A', 'B', 'C', 'D', 'E'],
    'Ventas_2024': [120, 340, 560, 230, 150],
    'Ventas_2025': [200, 400, 600, 300, 180]
}

df = pd.DataFrame(datos)

# 1. Calcular el porcentaje de crecimiento y agregar la columna 'Crecimiento'
df['Crecimiento'] = ((df['Ventas_2025'] - df['Ventas_2024']) / df['Ventas_2024']) * 100

# 2. Identificar el producto con mayor crecimiento
producto_mayor_crecimiento = df.loc[df['Crecimiento'].idxmax()]

print("DataFrame con columna Crecimiento:\n", df)
print("\nProducto con mayor crecimiento:")
print(producto_mayor_crecimiento)


DataFrame con columna Crecimiento:
   Producto  Ventas_2024  Ventas_2025  Crecimiento
0        A          120          200    66.666667
1        B          340          400    17.647059
2        C          560          600     7.142857
3        D          230          300    30.434783
4        E          150          180    20.000000

Producto con mayor crecimiento:
Producto               A
Ventas_2024          120
Ventas_2025          200
Crecimiento    66.666667
Name: 0, dtype: object


Parte 5: Resolución de ecuaciones

In [19]:
def resolver_ecuacion_primer_grado(a, b):
    """
    Resuelve una ecuación de primer grado de la forma ax + b = 0.

    Args:
        a: Coeficiente de x.
        b: Término independiente.

    Returns:
        El valor de x que resuelve la ecuación.
        Retorna un mensaje si la ecuación no tiene solución única.
    """
    if a == 0:
        if b == 0:
            return "La ecuación tiene infinitas soluciones (0 = 0)."
        else:
            return "La ecuación no tiene solución (0 = b)."
    else:
        x = -b / a
        return x

# Ejemplo de uso:
a1 = 2
b1 = 4
solucion1 = resolver_ecuacion_primer_grado(a1, b1)
print(f"Para la ecuación {a1}x + {b1} = 0, la solución es x = {solucion1}")

a2 = 0
b2 = 5
solucion2 = resolver_ecuacion_primer_grado(a2, b2)
print(f"Para la ecuación {a2}x + {b2} = 0, la solución es {solucion2}")

a3 = 0
b3 = 0
solucion3 = resolver_ecuacion_primer_grado(a3, b3)
print(f"Para la ecuación {a3}x + {b3} = 0, la solución es {solucion3}")

Para la ecuación 2x + 4 = 0, la solución es x = -2.0
Para la ecuación 0x + 5 = 0, la solución es La ecuación no tiene solución (0 = b).
Para la ecuación 0x + 0 = 0, la solución es La ecuación tiene infinitas soluciones (0 = 0).


In [20]:
import cmath # Importamos cmath para manejar números complejos

def resolver_ecuacion_segundo_grado(a, b, c):
    """
    Resuelve una ecuación de segundo grado de la forma ax^2 + bx + c = 0
    usando la fórmula general.

    Args:
        a: Coeficiente de x^2.
        b: Coeficiente de x.
        c: Término independiente.

    Returns:
        Una tupla con las dos soluciones (pueden ser reales o complejas).
        Retorna un mensaje si el coeficiente 'a' es cero.
    """
    if a == 0:
        return "El coeficiente 'a' no puede ser cero para una ecuación de segundo grado."

    # Calcular el discriminante
    delta = (b**2) - 4*(a*c)

    # Calcular las soluciones
    x1 = (-b - cmath.sqrt(delta)) / (2*a)
    x2 = (-b + cmath.sqrt(delta)) / (2*a)

    return x1, x2

# Ejemplo de uso:
a_s1, b_s1, c_s1 = 1, -5, 6  # x^2 - 5x + 6 = 0 -> (x-2)(x-3) = 0
soluciones1 = resolver_ecuacion_segundo_grado(a_s1, b_s1, c_s1)
print(f"Para la ecuación {a_s1}x^2 + {b_s1}x + {c_s1} = 0, las soluciones son: {soluciones1}")

a_s2, b_s2, c_s2 = 1, 2, 1   # x^2 + 2x + 1 = 0 -> (x+1)^2 = 0
soluciones2 = resolver_ecuacion_segundo_grado(a_s2, b_s2, c_s2)
print(f"Para la ecuación {a_s2}x^2 + {b_s2}x + {c_s2} = 0, las soluciones son: {soluciones2}")

a_s3, b_s3, c_s3 = 1, 1, 1   # x^2 + x + 1 = 0
soluciones3 = resolver_ecuacion_segundo_grado(a_s3, b_s3, c_s3)
print(f"Para la ecuación {a_s3}x^2 + {b_s3}x + {c_s3} = 0, las soluciones son: {soluciones3}")

a_s4, b_s4, c_s4 = 0, 2, 3
soluciones4 = resolver_ecuacion_segundo_grado(a_s4, b_s4, c_s4)
print(f"Para la ecuación {a_s4}x^2 + {b_s4}x + {c_s4} = 0, la solución es: {soluciones4}")

Para la ecuación 1x^2 + -5x + 6 = 0, las soluciones son: ((2+0j), (3+0j))
Para la ecuación 1x^2 + 2x + 1 = 0, las soluciones son: ((-1+0j), (-1+0j))
Para la ecuación 1x^2 + 1x + 1 = 0, las soluciones son: ((-0.5-0.8660254037844386j), (-0.5+0.8660254037844386j))
Para la ecuación 0x^2 + 2x + 3 = 0, la solución es: El coeficiente 'a' no puede ser cero para una ecuación de segundo grado.
